language: ruby
sudo: false
before_install:
  - gem install bundler -v 1.10.6
script: bundle exec rake
addons:
  code_climate:
    repo_token: ae398c193255da8c5e030cb6251f053c76757635e5215e65efa32f52d003a519
  apt:
    packages:
      - libmagic-dev
      - libimage-exiftool-perl
cache: bundler
matrix:
  include:
    - rvm: 2.3.0
      env: COVERAGE=1 DEPLOY=1
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0

    - rvm: jruby-9.0
      env: SMOKE_TEST_ONLY=1

    - rvm: rbx-3.2
      env: SMOKE_TEST_ONLY=1
    - rvm: rbx-2.7
      env: SMOKE_TEST_ONLY=1
  fast_finish: true
deploy:
  provider: rubygems
  on:
    repo: henrylawson/photish
    condition: "$DEPLOY = 1"
    branch: master
    tags: true
  api_key:
    secure: nFNY85dNmvdhc8H2t/tIiv0xTeWctitZSs2WtlVzOFpbNFac9rqd4ZhNQb/l2QiukquMdbWVzSr2uPZ+gJwhV/yWtX+xNbnPHdW/u5upX5PO9SNZImx8iVS95bViW+zygp3rZvVS6oVeIg4xAzuBMlviomYhp8lGRISWAM5efznK+NkLw16BiiDVQQ3KKLst0Ydo2TIzjkpfeFyNK9qj0Joxqllojo+QVBFUN+vHQcC2VgOQIJjCKshlRKDtMwvvt5+qjBPs5IsTwWkySkkum3WRLxwUXHoMqKqxbYfgXtr2A7KUKiGkK9L2zVYOYCErKDuS+YgQ3AgxnFsToOR8hp6SRv1WhR8Vix67u3A7dRmJ1hdyt0Re5+LyvHAuKXuUB6gJ8rbWpf56i4fbGCjl9IVE4YB+PfwRDwBAttXQTtYZE7AuseH+qdUYPRq3zLlYIcFxEliyNhh5Ud8aBh+ciM2R7ql0wA2Fu8tOK/2beoBWjifZc0z/B/hDHO4JGsphJaz59wPk/3DV6sCmaS4iMPAKtoyRdTyUN/hnzpq99LOEoQLCWUteWet5saV0svOQ3THRTZYO2mUX18Yb1Xjrm6iGhpjOMueBn+X12WLSXgHLuWV07/30cFdUOuhrGGu68weoMUY060PIdslUFtygSWIVVtvDpX1W52MLZyINeaA=
