language: ruby
sudo: false
before_install:
  - gem install bundler -v 1.10.6
script: bundle exec rake
addons:
  code_climate:
    repo_token: ae398c193255da8c5e030cb6251f053c76757635e5215e65efa32f52d003a519
  apt:
    packages:
      - libmagic-dev
      - libimage-exiftool-perl
cache: bundler
matrix:
  include:
    - rvm: ruby-head
    - rvm: 2.3.0
      env: COVERAGE=1
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
    - rvm: jruby-head
    - rvm: jruby-9.0
    - rvm: rbx-head
    - rvm: rbx-3.2
    - rvm: rbx-3
    - rvm: rbx-2
  allow_failures:
    - rvm: rbx-head
    - rvm: rbx-3
