language: ruby
sudo: false
before_install:
  - gem install bundler -v 1.10.6
script: bundle exec rake
addons:
  code_climate:
    repo_token: ae398c193255da8c5e030cb6251f053c76757635e5215e65efa32f52d003a519
  apt:
    packages:
      - libmagic-dev
      - libimage-exiftool-perl
cache: bundler
matrix:
  include:
    - rvm: ruby-head
    - rvm: 2.3.0
      env: COVERAGE=1
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0

    - rvm: jruby-head
    - rvm: jruby-9.0
      env: SMOKE_TEST_ONLY=1

    - rvm: rbx
    - rvm: rbx-3.2
      env: SMOKE_TEST_ONLY=1
    - rvm: rbx-2
      env: SMOKE_TEST_ONLY=1
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
