language: ruby
rvm:
  - 2.2.4
sudo: false
before_install:
  - gem install bundler -v 1.10.6
script: rake
addons:
  code_climate:
    repo_token: ae398c193255da8c5e030cb6251f053c76757635e5215e65efa32f52d003a519
  apt:
    packages:
      - libmagic-dev
      - libimage-exiftool-perl
cache: bundler
