language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-9.0
  - jruby-head
  - rbx-2
  - rbx-3.2
sudo: false
before_install:
  - gem install bundler -v 1.10.6
script: bundle exec rake
addons:
  code_climate:
    repo_token: ae398c193255da8c5e030cb6251f053c76757635e5215e65efa32f52d003a519
  apt:
    packages:
      - libmagic-dev
      - libimage-exiftool-perl
cache: bundler
matrix:
  include:
    - rvm: 2.3.0
      env: COVERAGE=true
  fast_finish: true
  allow_failures:
    - rvm: jruby-9.0
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-3.2
