language: ruby
sudo: false
before_install:
  - gem install bundler -v 1.10.6
script: bundle exec rake
addons:
  apt:
    packages:
      - libmagic-dev
      - libimage-exiftool-perl
cache: bundler
matrix:
  include:
    - rvm: jruby-9.0
      env: SMOKE_TEST_ONLY=1
    - rvm: rbx-3.2
      env: SMOKE_TEST_ONLY=1
    - rvm: rbx-2.7
      env: SMOKE_TEST_ONLY=1
